/*
 * Designed and developed by 2026 skydoves (Jaewoong Eum)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.skydoves.navgraph.gradle

import org.gradle.api.Project
import org.gradle.testfixtures.ProjectBuilder
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

/** Pins the Mermaid export — the artifact that ends up pasted into a README, so its syntax has to be exact. */
class NavMermaidTest {

  private fun export(
    manifest: String,
    configure: ExportNavGraphMermaidTask.() -> Unit = {},
  ): String {
    val project: Project = ProjectBuilder.builder().build()
    val task = project.tasks.register(
      "exportNavGraphMermaid",
      ExportNavGraphMermaidTask::class.java,
    ).get()
    task.manifest.set(
      project.layout.buildDirectory.file("test/nav-graph.json").get().asFile.apply {
        parentFile.mkdirs()
        writeText(manifest)
      },
    )
    val out = project.layout.buildDirectory.file("out/nav-graph.mmd").get().asFile
    task.outputFile.set(out)
    task.configure()
    task.export()
    return out.readText()
  }

  @Test
  fun rendersAFlowchartWithPositionalIdsAndAStartClass() {
    val mmd = export(MANIFEST)
    assertEquals(
      listOf(
        "%% Generated by the navgraph 'exportNavGraphMermaid' task — do not edit by hand.",
        "flowchart LR",
        "  n0[\"HomeScreen\"]",
        "  n1[\"Profile\"]",
        "  n0 -->|\"go\"| n1",
        "  n1 -.-> n0",
        "  classDef navgraphStart fill:#ede7f6,stroke:#6750a4,stroke-width:2px;",
        "  class n0 navgraphStart",
      ),
      mmd.trim().lines(),
    )
  }

  @Test
  fun honorsTheRequestedDirection() {
    assertTrue("flowchart TB" in export(MANIFEST) { direction.set("tb") })
    // An unrecognised value falls back rather than emitting a flowchart Mermaid cannot parse.
    assertTrue("flowchart LR" in export(MANIFEST) { direction.set("sideways") })
  }

  @Test
  fun wrapsInAMarkdownFenceOnRequest() {
    val md = export(MANIFEST) { markdown.set(true) }
    assertTrue(md.startsWith("```mermaid\n"))
    assertTrue(md.trimEnd().endsWith("```"))
  }

  @Test
  fun writesNoFenceByDefault() {
    assertFalse("```" in export(MANIFEST))
  }

  @Test
  fun escapesLabelCharactersMermaidWouldChokeOn() {
    val manifest = """
      {
        "nodes": [
          { "id": "x.A", "route": "A" },
          { "id": "x.B", "route": "B" }
        ],
        "edges": [ { "from": "x.A", "to": "x.B", "label": "say \"hi\" <now> & wait" } ]
      }
    """.trimIndent()
    val line = export(manifest).lines().single { "-->" in it }
    assertEquals("  n0 -->|\"say &quot;hi&quot; &lt;now&gt; &amp; wait\"| n1", line)
  }

  @Test
  fun scopesToAPackagePrefix() {
    val manifest = """
      {
        "nodes": [
          { "id": "com.app.feed.Feed", "route": "Feed" },
          { "id": "com.app.other.Other", "route": "Other" }
        ],
        "edges": [ { "from": "com.app.feed.Feed", "to": "com.app.other.Other" } ]
      }
    """.trimIndent()
    val mmd = export(manifest) { packageFilter.set("com.app.feed") }
    assertTrue("Feed" in mmd)
    assertFalse("Other" in mmd)
    // The cross-feature transition goes with it, so the flowchart never references a node it did not declare.
    assertFalse("-->" in mmd)
  }

  @Test
  fun anEmptyGraphIsStillAValidFlowchart() {
    val mmd = export("""{ "nodes": [], "edges": [] }""")
    assertTrue("flowchart LR" in mmd)
    assertFalse("classDef" in mmd)
  }

  private companion object {
    // Home has a @NavDestination (so its label is the composable's name), Profile does not; the back edge is
    // inferred, so it must render dotted.
    val MANIFEST = """
      {
        "nodes": [
          { "id": "x.Home", "route": "Home", "start": true, "clickTargetFqn": "x.HomeScreen" },
          { "id": "x.Profile", "route": "Profile" }
        ],
        "edges": [
          { "from": "x.Home", "to": "x.Profile", "label": "go" },
          { "from": "x.Profile", "to": "x.Home", "confidence": "INFERRED" }
        ]
      }
    """.trimIndent()
  }
}
