/*
 * Designed and developed by 2026 skydoves (Jaewoong Eum)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.skydoves.navgraph.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction

/**
 * Renders the graph as a Mermaid `flowchart` — the one export that needs no viewer. GitHub, GitLab, Obsidian, and
 * most docs sites render a ```` ```mermaid ```` block natively, so the navigation graph can live in the README and
 * be regenerated on every build instead of going stale as a checked-in screenshot.
 *
 * Node ids are positional (`n0`, `n1`, … in node-id order) rather than derived from the route FQN: Mermaid ids
 * cannot contain dots or quotes, and a positional id sidesteps every escaping question while staying stable for a
 * given graph. Declared transitions draw solid (`-->`), inferred ones dotted (`-.->`) — the same distinction the
 * canvas and the other exports make.
 */
@CacheableTask
public abstract class ExportNavGraphMermaidTask : DefaultTask() {

  @get:InputFile
  @get:PathSensitive(PathSensitivity.RELATIVE)
  public abstract val manifest: RegularFileProperty

  /** "" = the whole graph; else a package prefix, matching the other exports' `-Pnavgraph.export.package`. */
  @get:Input
  @get:Optional
  public abstract val packageFilter: Property<String>

  /** Flowchart direction: `LR` (default), `TB`, `RL`, or `BT`. */
  @get:Input
  @get:Optional
  public abstract val direction: Property<String>

  /** Wrap the output in a ```` ```mermaid ```` fence, ready to paste (or `include`) into a markdown file. */
  @get:Input
  @get:Optional
  public abstract val markdown: Property<Boolean>

  @get:OutputFile
  public abstract val outputFile: RegularFileProperty

  @TaskAction
  public fun export() {
    val pkg = packageFilter.orNull.orEmpty()
    val graph = filterGraphByPackage(parseGraph(manifest.get().asFile.readText()), pkg)
    if (pkg.isNotBlank() && graph.nodes.isEmpty()) {
      logger.warn("navgraph: no destinations under package '$pkg'; exporting an empty graph.")
    }

    val flowchart = render(graph)
    val text = if (markdown.orNull == true) "```mermaid\n$flowchart```\n" else flowchart
    val out = outputFile.get().asFile
    out.parentFile?.mkdirs()
    out.writeText(text)
    logger.lifecycle(
      "navgraph: wrote ${out.path} — ${graph.nodes.size} nodes, ${graph.edges.size} edges.",
    )
  }

  private fun render(graph: HGraph): String {
    // Distinct by id first: a positional id is only stable if each node declares exactly one.
    val nodes = graph.nodes.distinctBy { it.id }.sortedBy { it.id }
    val ids = nodes.mapIndexed { index, node -> node.id to "n$index" }.toMap()
    val startIds = nodes.filter { it.start }.map { ids.getValue(it.id) }
    return buildString {
      appendLine("%% Generated by the navgraph 'exportNavGraphMermaid' task — do not edit by hand.")
      appendLine("flowchart ${normalizedDirection()}")
      nodes.forEach { node ->
        appendLine("  ${ids.getValue(node.id)}[\"${escape(node.displayLabel())}\"]")
      }
      graph.edges
        .mapNotNull { edge ->
          val from = ids[edge.from] ?: return@mapNotNull null
          val to = ids[edge.to] ?: return@mapNotNull null
          val arrow = if (edge.inferred) "-.->" else "-->"
          val label = edge.label?.takeIf {
            it.isNotEmpty()
          }?.let { "|\"${escape(it)}\"|" }.orEmpty()
          "  $from $arrow$label $to"
        }
        .sorted()
        .forEach(::appendLine)
      if (startIds.isNotEmpty()) {
        appendLine("  classDef navgraphStart fill:#ede7f6,stroke:#6750a4,stroke-width:2px;")
        appendLine("  class ${startIds.joinToString(",")} navgraphStart")
      }
    }
  }

  private fun normalizedDirection(): String =
    direction.orNull?.uppercase()?.takeIf { it in DIRECTIONS } ?: "LR"

  private companion object {
    val DIRECTIONS = setOf("LR", "RL", "TB", "TD", "BT")

    /**
     * Mermaid reads a quoted label as text but still resolves entities, so every character that would end or
     * reshape the declaration is written as one rather than dropped. `|` matters most: an edge label is delimited
     * by pipes, so a bare one inside it is a parse error. `#` is Mermaid's own entity marker, so it is escaped
     * first, and `&` before the HTML entities, or the escapes would escape each other.
     */
    fun escape(text: String): String = text
      .replace("#", "#35;")
      .replace("&", "&amp;")
      .replace("|", "#124;")
      .replace("\"", "&quot;")
      .replace("<", "&lt;")
      .replace(">", "&gt;")
      .replace("[", "#91;")
      .replace("]", "#93;")
      .replace("\n", " ")
      .replace("\r", " ")
  }
}
